### Create New Account 
POST http://localhost:8080/finance/ HTTP/1.1 
content-type: application/json

{

"financetye" : "poi",
"tag":"investment",
"invDt" : "2015-01-01", "amt" : 159

}

### Create New Invoice with Customer 
POST http://localhost:8080/finance/user HTTP/1.1 
content-type: application/json

{
"client" : "Paytm", "invDt" : "2015-01-01", "amt" : 1233, "customerId" : 1
}

### Get All Invoices GET http://localhost:8080/finance/

### Delete Invoice By Id DELETE http://localhost:8080/invoice/2

### Invoice By Id GET http://localhost:8080/invoice/4

### Create New Account

PUT http://localhost:8080/invoice/ HTTP/1.1 
content-type: application/json

{
"id" : 10, "client" : "ooo", "invDt" : "1990-01-01", "amt" : 70000
}

### List All Customer Invoices GET http://localhost:8080/invoice/customer/5