POST http://localhost:8080/users/register
Content-Type: application/json

{ "name":"ricky", "email": "ricky@gmail.com", "password": "ricky12345" }

### 
POST http://localhost:8080/users/login
Content-Type: application/json

{ "email": "ricky@gmail.com", "password": "ricky12345" } 
### 
DELETE http://localhost:8080/users/all

### Forgot Password 
POST http://localhost:8080/user/login/forgotpass
content-type: application/json

{
"email": "rithvikchinnu@gmail.com"
}