POST http://localhost:8080/users/register
Content-Type: application/json

{ "name":"qwerty", "email": "qwerty@gmail.com", "password": "jla;f;a" }

### POST http://localhost:8080/login Content-Type: application/json

{ "email": "qwerty@gmail.com", "password": "jla;f;a" } 
### DELETE http://localhost:8080/users/all